### PR TITLE
Proxy support

### PR DESCRIPTION
**Pull request by IceCodeNew**
Introduce `proxy` support.
Also switch all commands that are issuing `wget` to issuing `curl`.

### CODE REVIEW

**Comment by userdocs** [comment]
Thanks for the contribution.

Overall i have nothing against this pull. looks like a useful addition.

The curl change is well timed because i was thinking about this for another reason.

At a glance my first question is regarding how the option is used.

https://github.com/userdocs/qbittorrent-nox-static/blob/e62948e3de482d717ca360ec3f081a99bb5c7e5b/qbittorrent-nox-static-glibc.sh#L56#L77

Do we need to be specific here? I'd assume if they were using a proxy and using the switch i'd just let them past a url?

**Comment by IceCodeNew** [comment]
e.g.:
./qbittorrent-nox-static-glibc.sh -p "socks5h://127.0.0.1:1080"
while the script running, the actual arg for proxy passed to `curl` is `curl -x"socks5h://127.0.0.1:1080"`.

I used to get trapped here because I was assuming the arg for proxy should be separate from switch `-x` by a space. And the `curl` just kept complaining.
So I choose to implement an `-p` switch for this project, and hide all this detail below the surface.

**Comment by userdocs** [comment]
It looks like you are matching against a specific prefix, http, socks. Maybe we don't need to be that specific. just let them use a url.

Also this shows there are two methods to implement this.

https://www.cyberciti.biz/faq/linux-unix-curl-command-with-proxy-username-password-http-options/

**Comment by IceCodeNew** [comment]
> Maybe we don't need to be that specific. just let them use a url.

That make sense. I will change it.

**Comment by IceCodeNew** [comment]
Are we clear to merge this PR now?
@userdocs

**Comment by userdocs** [comment]
I am not in a rush to merge this. I have some thoughts and ideas i want to implement but right now i don't have the time to process it all and merge a pull. it needs a little more time.

**Comment by userdocs** [comment]
one reason for this is i have a function i used i another build script i could apply to this change

https://github.com/userdocs/lftp-static/blob/master/build-script.sh#L215#L223

I just need to add the git support.

**Comment by IceCodeNew** [comment]
This PR is for people who live in a country where GitHub is far from been regard as basic infrastructure. As it seems like the owner of this repo has little interest in this PR. I'll close it now.

**Pull request closed without merging**
